// MAJOR_COURSE_SETS (src/course-sets.generated.ts) is a precomputed, checked-in constant: every
// major's literal course ids, so the double-major notice pre-filter (apps/web/lib/advisor/
// programs.ts) can score a plan against ~100 majors without loading each one's Program. It's
// generated by `npm run build:course-sets` (scripts/build-course-sets.ts). This test recomputes
// the same thing from the live Programs and fails if the checked-in file has drifted -- e.g. a
// batch added a major but forgot to regenerate it (docs/project/program-batches.md).

import { programCourseIds } from "@turboterp/audit";
import { describe, expect, it } from "vitest";
import { MAJOR_COURSE_SETS } from "../src/course-sets.generated.ts";
import { PROGRAMS } from "../src/registry.ts";

describe("MAJOR_COURSE_SETS", () => {
  it("has one entry per major, matching each major's own literal course ids", async () => {
    const majors = PROGRAMS.filter((p) => p.kind === "major");
    const fresh: Record<string, string[]> = {};
    for (const entry of majors) {
      fresh[entry.id] = programCourseIds(await entry.load());
    }
    expect(MAJOR_COURSE_SETS).toEqual(fresh);
  }, 60_000); // loads every program file; slow under load as the registry grows

  it("carries no entries for non-major programs", () => {
    const nonMajors = new Set(PROGRAMS.filter((p) => p.kind !== "major").map((p) => p.id));
    expect(Object.keys(MAJOR_COURSE_SETS).some((id) => nonMajors.has(id))).toBe(false);
  });
});
