// src/registry.generated.ts is a checked-in constant, generated by `npm run build:registry`
// (scripts/build-registry.ts) from every program file's own ProgramMeta. This test rebuilds the
// same thing from the live program files and fails if the checked-in file has drifted -- e.g. a
// batch added a program, or edited its ProgramMeta, but forgot to regenerate (same pattern as
// course-sets.test.ts for course-sets.generated.ts; docs/project/program-batches.md).
import { describe, expect, it } from "vitest";
import { buildProgramEntries } from "../scripts/registry-builder.ts";
import { PROGRAMS } from "../src/registry.generated.ts";

describe("registry.generated.ts", () => {
  it("matches what the generator currently produces from the program files", async () => {
    const fresh = await buildProgramEntries();
    const committed = PROGRAMS.map(({ load: _load, ...rest }) => rest);
    const freshComparable = fresh.map(({ importPath: _importPath, exportName: _exportName, ...rest }) => rest);
    expect(committed).toEqual(freshComparable);
  }, 60_000); // scans and loads every program file; slow under load as the registry grows
});
