// Audits the course equivalences (Twins) in the Schedule of Classes snapshots and how program files
// name courses that are Twins. Writes docs/project/equivalence-audit.md.
//
//   node scripts/equivalence-audit.ts [cacheDir]
//
// cacheDir defaults to the main checkout's packages/course-data/.cache (every soc-*.json in it is
// read). This script imports @turboterp/programs; the plan package itself must not (programs depends
// on plan), so it is not in plan's package.json.

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { programCourseIds, type Program } from "@turboterp/audit";
import type { Course } from "@turboterp/course-data";
import { PROGRAMS } from "@turboterp/programs";
import { buildCatalog } from "../src/catalog.ts";
import { parseCourseTwins, TWIN_KINDS, twinsOf, type TwinKind } from "../src/twins.ts";

const git = (...args: string[]) => execFileSync("git", args, { encoding: "utf8" }).trim();
const root = git("rev-parse", "--show-toplevel");
const mainCheckout = dirname(resolve(git("rev-parse", "--path-format=absolute", "--git-common-dir")));
const cacheDir = process.argv[2] ?? join(mainCheckout, "packages", "course-data", ".cache");

const files = readdirSync(cacheDir).filter((f) => /^soc-\d+\.json$/.test(f)).sort();
const lists = files.map((f) => (JSON.parse(readFileSync(join(cacheDir, f), "utf8")) as { courses: Course[] }).courses);
const catalog = buildCatalog(...lists);
const courses = new Map<string, Course>();
for (const c of lists.flat()) if (!courses.has(c.id)) courses.set(c.id, c);

const KIND_NAME: Record<TwinKind, string> = { renumbered: "Renumbered (Formerly)", crossListed: "Cross-listed", creditOnly: "Credit-only" };
const out: string[] = [];
const say = (s = "") => out.push(s);
const names = (ids: Iterable<string>) => [...ids].sort().join(", ");

say("# Course equivalence audit");
say();
say(`Generated by \`packages/plan/scripts/equivalence-audit.ts\` from ${files.join(", ")} (${courses.size} courses). Terms: Twin, Renumbered Twin, Cross-listed Twin, Credit-only Twin (CONTEXT.md). Rules: program-sources/course-equivalence.md.`);

// (a) counts
say();
say("## (a) Counts per Twin kind");
say();
say("| Kind | Courses with a line | Distinct Twin pairs (symmetric) |");
say("|---|---|---|");
const onesided: Record<TwinKind, { a: string; b: string }[]> = { renumbered: [], crossListed: [], creditOnly: [] };
const partnerMissing: Record<TwinKind, number> = { renumbered: 0, crossListed: 0, creditOnly: 0 };
for (const kind of TWIN_KINDS) {
  let withLine = 0;
  const pairs = new Set<string>();
  for (const c of catalog.values()) {
    const named = c.twins?.[kind];
    if (!named) continue;
    withLine++;
    for (const b of named) {
      pairs.add([c.id, b].sort().join("|"));
      const other = catalog.get(b);
      if (!other) partnerMissing[kind]++;
      else if (!other.twins?.[kind]?.includes(c.id)) onesided[kind].push({ a: c.id, b });
    }
  }
  say(`| ${KIND_NAME[kind]} | ${withLine} | ${pairs.size} |`);
}

// (b) one-sided pairs
say();
say("## (b) One-sided pairs (A names B, B is in a snapshot but does not name A)");
say();
for (const kind of TWIN_KINDS) {
  say(`### ${KIND_NAME[kind]}: ${onesided[kind].length} one-sided (and ${partnerMissing[kind]} naming a course in neither snapshot)`);
  say();
  if (onesided[kind].length > 0) say(onesided[kind].map((p) => `${p.a} -> ${p.b}`).join("; "));
  say();
}

// (c) tokens that are not course codes
say("## (c) Tokens that are not course codes");
say();
const bad: string[] = [];
for (const c of courses.values()) {
  const { rejected } = parseCourseTwins(c);
  for (const t of rejected) bad.push(`${c.id}: ${t}`);
}
say(`${bad.length} token(s).`);
say();
for (const b of bad) say(`- ${b}`);

// (d) program course ids
const programs: { name: string; program: Program }[] = [];
for (const entry of PROGRAMS) programs.push({ name: `${entry.name} (${entry.id})`, program: await entry.load() });

const newCodeOf = new Map<string, Set<string>>(); // old code -> courses that are its Renumbered Twins
for (const id of courses.keys()) for (const old of twinsOf(catalog, id).renumbered) (newCodeOf.get(old) ?? newCodeOf.set(old, new Set()).get(old)!).add(id);

const classes = { snapshot: 0, renumbered: 0, neither: 0 };
const renumberedBy = new Map<string, string[]>();
const neitherBy = new Map<string, string[]>();
const seen = new Set<string>();
for (const { name, program } of programs) {
  for (const id of programCourseIds(program)) {
    const first = !seen.has(id);
    seen.add(id);
    if (courses.has(id)) {
      if (first) classes.snapshot++;
    } else if (newCodeOf.has(id)) {
      if (first) classes.renumbered++;
      (renumberedBy.get(name) ?? renumberedBy.set(name, []).get(name)!).push(`${id} -> ${names(newCodeOf.get(id)!)}`);
    } else {
      if (first) classes.neither++;
      (neitherBy.get(name) ?? neitherBy.set(name, []).get(name)!).push(id);
    }
  }
}
say();
say(`## (d) Course ids named in program files (${seen.size} distinct, ${programs.length} programs)`);
say();
say(`- In a snapshot: ${classes.snapshot}`);
say(`- A Renumbered Twin's old code (not itself in a snapshot): ${classes.renumbered}`);
say(`- In neither snapshot: ${classes.neither}`);
say();
say("### Old codes of Renumbered Twins, by program");
say();
for (const [name, ids] of [...renumberedBy].sort()) say(`- ${name}: ${ids.join("; ")}`);
say();
say("### In neither snapshot, by program");
say();
for (const [name, ids] of [...neitherBy].sort()) say(`- ${name}: ${ids.join(", ")}`);

// (e) requirements naming one Cross-listed Twin but not the other
say();
say("## (e) Requirements that name one Cross-listed Twin but not the other");
say();
const lines: string[] = [];
for (const { name, program } of programs) {
  for (const req of program.requirements) {
    const ids = new Set(programCourseIds({ ...program, requirements: [req] }));
    const missing: string[] = [];
    for (const a of ids) for (const b of twinsOf(catalog, a).crossListed) if (!ids.has(b)) missing.push(`${a} without ${b}`);
    if (missing.length > 0) lines.push(`- ${name}, \`${req.id}\`: ${[...new Set(missing)].join("; ")}`);
  }
}
say(`${lines.length} requirement(s).`);
say();
for (const l of lines.sort()) say(l);

writeFileSync(join(root, "docs", "project", "equivalence-audit.md"), out.join("\n") + "\n");
console.log(
  `a: ${TWIN_KINDS.map((k) => `${k} one-sided ${onesided[k].length}`).join(", ")}; c: ${bad.length}; d: ${JSON.stringify(classes)}; e: ${lines.length}`,
);
