// Regenerates src/course-sets.generated.ts: every major's literal course ids (programCourseIds),
// precomputed so the double-major notice pre-filter (apps/web/lib/advisor/programs.ts) can score
// a plan against every major without loading each one's Program (which pulls in the audit's
// requirements and, transitively, HiGHS).
//
// Run `npm run build:course-sets -w @turboterp/programs` after adding or changing a major
// (docs/project/program-batches.md); test/course-sets.test.ts fails if this drifts.

import { programCourseIds } from "@turboterp/audit";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { PROGRAMS } from "../src/registry.ts";

async function main() {
  const majors = PROGRAMS.filter((p) => p.kind === "major");
  const entries: [string, string[]][] = [];
  for (const entry of majors) {
    const program = await entry.load();
    entries.push([entry.id, programCourseIds(program)]);
  }
  const body = entries.map(([id, courses]) => `  ${JSON.stringify(id)}: ${JSON.stringify(courses)},`).join("\n");
  const out = `// GENERATED by scripts/build-course-sets.ts -- do not hand-edit.
// Every major's literal course ids (@turboterp/audit's programCourseIds), used only to pre-filter
// which undeclared majors are worth auditing for a double-major notice (apps/web/lib/advisor/
// programs.ts). Regenerate with \`npm run build:course-sets -w @turboterp/programs\` after adding
// or changing a major; test/course-sets.test.ts fails if this drifts from the live Programs.

export const MAJOR_COURSE_SETS: Record<string, string[]> = {
${body}
};
`;
  const target = fileURLToPath(new URL("../src/course-sets.generated.ts", import.meta.url));
  writeFileSync(target, out);
  console.log(`Wrote ${entries.length} major course set(s) to ${target}`);
}

main();
