// Regenerates src/registry.generated.ts from every program file's own ProgramMeta (see
// registry-builder.ts and packages/audit/src/audit.ts). Run `npm run build:registry
// -w @turboterp/programs` after adding, removing or renaming a program (or its ProgramMeta);
// test/registry-generated.test.ts fails if this drifts.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { buildProgramEntries } from "./registry-builder.ts";

function tsLiteral(v: unknown): string {
  return JSON.stringify(v);
}

function sourcesLiteral(sources: { catalog?: string; department?: string }): string {
  const fields: string[] = [];
  if (sources.catalog !== undefined) fields.push(`catalog: ${tsLiteral(sources.catalog)}`);
  if (sources.department !== undefined) fields.push(`department: ${tsLiteral(sources.department)}`);
  return `{ ${fields.join(", ")} }`;
}

function notOpenToLiteral(gate: { programs?: string[]; colleges?: string[]; reason: string }): string {
  const fields: string[] = [];
  if (gate.programs !== undefined) fields.push(`programs: ${tsLiteral(gate.programs)}`);
  if (gate.colleges !== undefined) fields.push(`colleges: ${tsLiteral(gate.colleges)}`);
  fields.push(`reason: ${tsLiteral(gate.reason)}`);
  return `{ ${fields.join(", ")} }`;
}

async function main() {
  const entries = await buildProgramEntries();
  const body = entries
    .map((e) => {
      const fields: string[] = [
        `id: ${tsLiteral(e.id)}`,
        `name: ${tsLiteral(e.name)}`,
        ...(e.short !== undefined ? [`short: ${tsLiteral(e.short)}`] : []),
        `kind: ${tsLiteral(e.kind)}`,
        ...(e.major !== undefined ? [`major: ${tsLiteral(e.major)}`] : []),
        ...(e.track !== undefined ? [`track: ${tsLiteral(e.track)}`] : []),
        `college: ${tsLiteral(e.college)}`,
        `catalogYear: ${tsLiteral(e.catalogYear)}`,
        `verified: ${tsLiteral(e.verified)}`,
        `sources: ${sourcesLiteral(e.sources)}`,
        ...(e.notOpenTo !== undefined ? [`notOpenTo: ${notOpenToLiteral(e.notOpenTo)}`] : []),
        ...(e.onlyOpenTo !== undefined ? [`onlyOpenTo: ${notOpenToLiteral(e.onlyOpenTo)}`] : []),
        `load: () => import(${tsLiteral(e.importPath)}).then((m) => m.${e.exportName})`,
      ];
      return `  { ${fields.join(", ")} },`;
    })
    .join("\n");
  const out = `// GENERATED by scripts/build-registry.ts -- do not hand-edit.
// Every encoded UMD program the Advisor offers, assembled from each program file's own ProgramMeta
// (packages/audit/src/audit.ts) next to its Program: majors, then minors, then certificates, then
// special programs; within each kind, alphabetically by name except that a major's tracks stay
// together, the ProgramMeta.defaultTrack one first. Each \`load\` is a literal \`import()\` path, so
// a page listing every program never bundles their requirements -- each becomes its own chunk.
//
// Regenerate with \`npm run build:registry -w @turboterp/programs\` after adding, removing or
// renaming a program (or its ProgramMeta); test/registry-generated.test.ts fails if this drifts.
// See docs/project/program-batches.md.

import type { ProgramEntry } from "./registry-types.ts";

export const PROGRAMS: ProgramEntry[] = [
${body}
];
`;
  const target = fileURLToPath(new URL("../src/registry.generated.ts", import.meta.url));
  writeFileSync(target, out);
  console.log(`Wrote ${entries.length} program(s) to ${target}`);
}

main();
