// Accounts for every UMD lab course (docs/project/lab-pairs.md). Reads the current Testudo terms
// (.cache/soc-*.json), past terms (.cache/history/soc-*.json) and both UMD catalogs
// (.cache/catalog-courses.json), and lists every lab course that isn't some lecture's lab, standalone,
// or covered by a standalone rule. Run after each term refresh:
//
//   npm run lab-coverage -w @turboterp/course-data -- [--cache <dir>] [--write]
//
// --write rewrites test/fixtures/lab-courses.json (every lab course plus the courses that name one),
// src/lab-pairs.generated.ts (pairs derived from text in every source) and program-sources/labs.md
// (each unclassified lab's text, for the builders who classify them).

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { isLabCourse, labsByLecture, ruleFor, unclassifiedLabs, type LabPair, type LabSourceCourse } from "../src/lab-pairs.ts";
import type { Course, Section } from "../src/soc.ts";

const flag = process.argv.indexOf("--cache");
const cache = resolve(flag >= 0 ? process.argv[flag + 1]! : ".cache");
const socFiles = (dir: string) => (existsSync(dir) ? readdirSync(dir).filter((f) => /^soc-\d{6}\.json$/.test(f)).map((f) => join(dir, f)) : []);

// Newest record of each course wins: current terms, then past terms newest first, then the catalogs.
type Snapshot = { term: string; courses: Course[]; sections: Section[] };
const snapshots = [...socFiles(cache), ...socFiles(join(cache, "history"))]
  .map((p) => JSON.parse(readFileSync(p, "utf8")) as Snapshot)
  .sort((a, b) => b.term.localeCompare(a.term));
const labOnly = new Set<string>();
for (const s of snapshots) {
  const byCourse = new Map<string, Section[]>();
  for (const x of s.sections) byCourse.set(x.courseId, [...(byCourse.get(x.courseId) ?? []), x]);
  for (const [id, secs] of byCourse) {
    const types = secs.flatMap((x) => x.meetings.map((m) => m.type));
    if (types.length > 0 && types.every((t) => /\blab\b/i.test(t))) labOnly.add(id);
  }
}
const catalogFile = join(cache, "catalog-courses.json");
const catalogCourses: (Course & { source?: string })[] = existsSync(catalogFile) ? JSON.parse(readFileSync(catalogFile, "utf8")).courses : [];
const sourceOf = new Map<string, string>();
const all = new Map<string, LabSourceCourse>();
for (const s of snapshots) for (const c of s.courses) if (!all.has(c.id)) { all.set(c.id, c); sourceOf.set(c.id, `Testudo Schedule of Classes, ${s.term}`); }
for (const c of catalogCourses) if (!all.has(c.id)) { all.set(c.id, c); sourceOf.set(c.id, `UMD catalog, ${c.source ?? ""}`.trim()); }
for (const id of labOnly) { const c = all.get(id); if (c) all.set(id, { ...c, labOnly: true }); }
const courses = [...all.values()];

const missing = unclassifiedLabs(courses);
console.log(`lab-coverage: ${snapshots.map((s) => s.term).join(", ")} + ${catalogCourses.length} catalog courses: ${courses.filter(isLabCourse).length} lab courses (${courses.filter((c) => ruleFor(c)).length} by rule), ${missing.length} unclassified`);
for (const c of missing) console.log(`  ${c.id}  ${c.title}`);

if (process.argv.includes("--write")) {
  // Derived pairs: what the text links, cited to the record it came from.
  const derived: LabPair[] = [...labsByLecture(courses)].map(([lecture, labs]) => ({ lecture, labs, source: sourceOf.get(lecture) ?? sourceOf.get(labs[0]!) ?? "" }));
  writeFileSync(
    "src/lab-pairs.generated.ts",
    `// Written by \`npm run lab-coverage -w @turboterp/course-data -- --write\`; do not edit by hand.\nimport type { LabPair } from "./lab-pairs.ts";\n\nexport const DERIVED_PAIRS: LabPair[] = ${JSON.stringify(derived, null, 1)};\n`,
  );

  const labIds = new Set(courses.filter(isLabCourse).map((c) => c.id));
  const names = (c: LabSourceCourse) =>
    [...(c.texts.corequisite?.match(/[A-Z]{4}\d{3}[A-Z]?/g) ?? []), c.labPair?.with ?? "", /if taken with\s+([A-Z]{4}\d{3}[A-Z]?)/i.exec(c.genEdText ?? "")?.[1] ?? ""].some((id) => labIds.has(id));
  const fixture = courses
    .filter((c) => labIds.has(c.id) || names(c))
    .map((c) => ({
      id: c.id, department: c.department, title: c.title, credits: c.credits, genEd: c.genEd, genEdText: c.genEdText,
      ...(c.labPair ? { labPair: c.labPair } : {}), ...(c.labOnly ? { labOnly: true } : {}),
      permissionRequired: false,
      texts: { prerequisite: null, corequisite: c.texts.corequisite, restriction: null, creditOnlyGrantedFor: null, other: {} },
      description: "",
    }))
    .sort((a, b) => a.id.localeCompare(b.id));
  writeFileSync("test/fixtures/lab-courses.json", `${JSON.stringify({ sources: [...snapshots.map((s) => s.term), "catalogs"], courses: fixture }, null, 1)}\n`);

  const md = [
    "# Lab courses to classify",
    "",
    "Generated by `npm run lab-coverage -w @turboterp/course-data -- --write`. UMD's own text for each lab course not yet linked to a lecture, standalone, or covered by a rule. Cite the `Source` line in each entry.",
    "",
    ...missing.flatMap((c) => [
      `## ${c.id}: ${c.title} (${c.credits.min === c.credits.max ? c.credits.min : `${c.credits.min}-${c.credits.max}`} credits)${c.labOnly ? " [lab meetings only]" : ""}`,
      "",
      `- Source: ${sourceOf.get(c.id)}`,
      ...(c.texts.prerequisite ? [`- Prerequisite: ${c.texts.prerequisite}`] : []),
      ...(c.texts.corequisite ? [`- Corequisite: ${c.texts.corequisite}`] : []),
      ...(c.texts.restriction ? [`- Restriction: ${c.texts.restriction}`] : []),
      ...(c.texts.creditOnlyGrantedFor ? [`- Credit only granted for: ${c.texts.creditOnlyGrantedFor}`] : []),
      ...Object.entries(c.texts.other).map(([k, v]) => `- ${k}: ${v}`),
      `- Description: ${c.description.replace(/\s+/g, " ").trim()}`,
      "",
    ]),
  ];
  writeFileSync(resolve("../../program-sources/labs.md"), `${md.join("\n")}\n`);
  console.log(`wrote src/lab-pairs.generated.ts (${derived.length} pairs), test/fixtures/lab-courses.json (${fixture.length} courses), program-sources/labs.md (${missing.length} labs)`);
}
