// Writes docs/project/prereq-audit.md: every prerequisite/corequisite sentence pattern with one
// example and its parse, so a human checks one course per pattern instead of all of them.
//
//   node scripts/prereq-audit.ts            (run from packages/course-data)

import { readFileSync, writeFileSync } from "node:fs";
import { ambiguousPrecedence, creditAnomalies, describeRequirement, detectClasses, lostCodes, normalizeTemplate } from "../src/prereq-audit.ts";
import { mergeSnapshots } from "../src/merge-snapshots.ts";
import { parsePrerequisite } from "../src/prereqs.ts";
import type { Course } from "../src/soc.ts";

const OUT = "../../docs/project/prereq-audit.md";
const terms = ["202608", "202701"];
const courses = mergeSnapshots(
  terms.map((term) => ({ term, courses: (JSON.parse(readFileSync(`.cache/soc-${term}.json`, "utf8")) as { courses: Course[] }).courses })),
);

type Kind = "prerequisite" | "corequisite";
type Item = { id: string; text: string; flags: string[] };
const flagged: Record<string, Set<string>> = {};
const flagLines: string[] = [];
const noteFlag = (kind: Kind, id: string, flag: string, why: string, item: Item) => {
  (flagged[flag] ??= new Set()).add(`${kind}:${id}`);
  item.flags.push(flag);
  flagLines.push(`- ${id} (${kind}) **${flag}**: ${why}`);
};

const sections: string[] = [];
const templateCounts: Record<Kind, number> = { prerequisite: 0, corequisite: 0 };
let tid = 0;
const withKind = { prerequisite: 0, corequisite: 0 };

for (const kind of ["prerequisite", "corequisite"] as Kind[]) {
  const groups = new Map<string, Item[]>();
  for (const c of courses) {
    const text = c.texts[kind];
    if (!text) continue;
    withKind[kind]++;
    const item: Item = { id: c.id, text, flags: [] };
    // Corequisites go through the same parser; the tree shape is what matters.
    const tree = parsePrerequisite(text);
    if (!tree) noteFlag(kind, c.id, "unparsed", "nothing parsed", item);
    else {
      const lost = lostCodes(text, tree);
      if (lost.length) noteFlag(kind, c.id, "lost-code", lost.join(", "), item);
      for (const f of detectClasses(text, tree)) noteFlag(kind, c.id, `class-${f.cls}`, f.why, item);
    }
    if (ambiguousPrecedence(text)) noteFlag(kind, c.id, "ambiguous-precedence", "and/or mixed without parentheses", item);
    const key = normalizeTemplate(text);
    (groups.get(key) ?? groups.set(key, []).get(key)!).push(item);
  }
  const sorted = [...groups.entries()].sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]));
  templateCounts[kind] = sorted.length;
  const lines = [`## ${kind === "prerequisite" ? "Prerequisite" : "Corequisite"} templates (${sorted.length})`, ""];
  for (const [key, items] of sorted) {
    const id = `T${String(++tid).padStart(3, "0")}`;
    const ids = items.map((i) => i.id);
    const shown = ids.length > 30 ? `${ids.slice(0, 30).join(", ")} ... (+${ids.length - 30} more)` : ids.join(", ");
    // Prefer an example that carries a flag, so the reviewer sees the suspicious parse.
    const ex = items.find((i) => i.flags.length) ?? items[0]!;
    const tree = parsePrerequisite(ex.text);
    const tags = [...new Set(items.flatMap((i) => i.flags))];
    lines.push(
      `### ${id} (${items.length}) ${kind}`,
      "",
      `Pattern: \`${key.replace(/`/g, "'")}\``,
      "",
      tags.length ? `Flags: ${tags.join(", ")}` : "Flags: none",
      "",
      `Courses: ${shown}`,
      "",
      `Example ${ex.id}:`,
      "",
      `> ${ex.text.replace(/\n/g, " ")}`,
      "",
      `Parsed: ${tree ? describeRequirement(tree) : "(nothing)"}`,
      "",
      "Verdict:",
      "",
    );
  }
  sections.push(lines.join("\n"));
}

// Credits (snapshot values only; the Testudo HTML-derived value is the snapshot).
const credit: Record<string, string[]> = { "min>max": [], zero: [], variable: [] };
for (const c of courses) for (const a of creditAnomalies(c.credits)) credit[a]!.push(`${c.id} (${c.credits.min}-${c.credits.max})`);

const flagCounts = Object.entries(flagged).sort().map(([k, v]) => `- ${k}: ${v.size}`);
const out = [
  "# Prerequisite audit",
  "",
  "Generated by `packages/course-data/scripts/prereq-audit.ts` from soc-202608 + soc-202701 (merged, newest wins). Check one course per template and write a verdict.",
  "",
  "## Summary",
  "",
  `- Courses: ${courses.length}`,
  `- With prerequisite text: ${withKind.prerequisite} (${templateCounts.prerequisite} templates)`,
  `- With corequisite text: ${withKind.corequisite} (${templateCounts.corequisite} templates)`,
  "- Flagged (course-kind pairs) per detector:",
  ...(flagCounts.length ? flagCounts.map((l) => `  ${l}`) : ["  - none"]),
  `- Credits: ${credit.variable!.length} variable-credit, ${credit.zero!.length} zero-credit, ${credit["min>max"]!.length} with min>max`,
  "",
  "Detectors: unparsed; lost-code (a code in the text is in neither tree nor manual item, or is swallowed into a manual item); class-A waiver codes required; B excluded course required; C shorthand/slash not read; D required and optional at once; E grade phrase without a grade; F 'or equivalent' dropped; H 'one of the following' not an any; ambiguous-precedence (and/or mixed with no parentheses). Corequisite texts are parsed with the prerequisite parser.",
  "",
  "## Flags",
  "",
  ...(flagLines.length ? flagLines : ["None."]),
  "",
  "## Credits",
  "",
  `Source is the snapshot's own credits value only (no second source to compare).`,
  "",
  `- min>max: ${credit["min>max"]!.join(", ") || "none"}`,
  `- zero credits: ${credit.zero!.join(", ") || "none"}`,
  `- variable credits: ${credit.variable!.length} courses (first 40: ${credit.variable!.slice(0, 40).join(", ")})`,
  "",
  ...sections,
].join("\n");
writeFileSync(OUT, out);
console.log(`Wrote ${OUT}: ${courses.length} courses, ${templateCounts.prerequisite} prereq + ${templateCounts.corequisite} coreq templates`);
console.log(flagCounts.join("\n"));
