// Hand-classified labs for departments A–L (lab-pairs-m-z.ts has M–Z), from the UMD text in
// program-sources/labs.md. See lab-pairs.ts.
import type { LabPair, StandaloneLab, StandaloneRule } from "./lab-pairs.ts";

export const PAIRS: LabPair[] = [
  { lecture: "ANSC101", labs: ["ANSC103"], source: "Testudo Schedule of Classes, 202701: ANSC103 prerequisite 'Must have completed or be concurrently enrolled in ANSC101.'" },
  { lecture: "BIOE120", labs: ["BIOE121"], source: "Testudo Schedule of Classes, 202701: BIOE121 prerequisite 'Must have completed or be concurrently enrolled in BIOE120.'" },
  { lecture: "BSCI331", labs: ["BSCI332"], source: "Testudo Schedule of Classes, 202701: BSCI332 prerequisite 'Must have completed with a minimum grade of C- or be concurrently enrolled in BSCI331 or BSCI230.'" },
  { lecture: "BSCI230", labs: ["BSCI332"], source: "Testudo Schedule of Classes, 202701: BSCI332 prerequisite 'Must have completed with a minimum grade of C- or be concurrently enrolled in BSCI331 or BSCI230.'" },
  { lecture: "BSCI334", labs: ["BSCI335"], source: "Testudo Schedule of Classes, 202701: BSCI335 prerequisite 'Minimum grade of C- in BSCI160, (BSCI180 or BSCI161), and BSCI207; and must have completed with a minimum grade of C- or be concurrently enrolled in, BSCI334.'" },
  { lecture: "BSCI422", labs: ["BSCI423"], source: "Testudo Schedule of Classes, 202701: BSCI423 prerequisite 'Minimum grade of C- in (BSCI222 or HLSC322); and must have completed with a minimum grade of C-, or be concurrently enrolled in, BSCI422.'" },
  { lecture: "BSCI420", labs: ["BSCI425"], source: "Testudo Schedule of Classes, 202701: BSCI425 prerequisite 'Minimum grade of C- in [BSCI330 or (BSCI 331 and 332)] AND minimum grade of C- in (BSCI222 or HLSC322), AND minimum grade of C- in [CHEM237 or (CHEM231 and CHEM232)]; and must have completed with a minimum grade of C-, or be concurrently enrolled in, BSCI420.'" },
  { lecture: "CHEM271", labs: ["CHEM277"], source: "Testudo Schedule of Classes, 202701: CHEM277 prerequisite 'Minimum grade of C- in (CHEM241 and CHEM242) or CHEM247; and must have completed or be concurrently enrolled in CHEM271 or CHEM276.'" },
  { lecture: "CHEM276", labs: ["CHEM277"], source: "Testudo Schedule of Classes, 202701: CHEM277 prerequisite 'Minimum grade of C- in (CHEM241 and CHEM242) or CHEM247; and must have completed or be concurrently enrolled in CHEM271 or CHEM276.'" },
  { lecture: "CHEM481", labs: ["CHEM483"], source: "Testudo Schedule of Classes, 202701: CHEM483 prerequisite 'Must have completed or be concurrently enrolled in CHEM481.'" },
  { lecture: "CHEM482", labs: ["CHEM484"], source: "Testudo Schedule of Classes, 202701: CHEM484 prerequisite 'Must have completed or be concurrently enrolled in CHEM482.'" },
  { lecture: "ENBC351", labs: ["ENBC352"], source: "Testudo Schedule of Classes, 202701: ENBC352 prerequisite 'Minimum grade of C- or concurrently enrolled in ENBC351.'" },
  { lecture: "BSCI410", labs: ["BSCI415"], source: "UMD catalog, https://academiccatalog.umd.edu/undergraduate/approved-courses/bsci/: BSCI415 prerequisite 'Must have completed with a minimum grade of C-, or be concurrently enrolled in, BSCI410.'" },
  { lecture: "BSCI353", labs: ["BSCI454"], source: "UMD catalog, https://academiccatalog.umd.edu/undergraduate/approved-courses/bsci/: BSCI454 prerequisite 'Minimum grade of C- in BSCI330 or (BSCI331 and BSCI332); must have completed or be concurrently enrolled in BSCI353; and must have completed or be concurrently enrolled in PHYS122, PHYS132, or PHYS142.'" },
  { lecture: "BSCI392", labs: ["BSCI393","GEOL392"], source: "Testudo Schedule of Classes, 202601: BSCI393 prerequisite 'Must have completed or be concurrently enrolled in BSCI392.' | Testudo Schedule of Classes, 202601: GEOL392 prerequisite 'Must have completed or be concurrently enrolled in BSCI392.'" },
  { lecture: "BSCI483", labs: ["BSCI484"], source: "Testudo Schedule of Classes, 202608: BSCI484 prerequisite 'Minimum grade of C- in [BSCI180 or (BSCI161 and BSCI171)] AND minimum grade of C- in BSCI207; and must have completed with a minimum grade of C- in, or be concurrently enrolled in, BSCI483.'" },
  { lecture: "ANSC446", labs: ["ANSC447"], source: "Testudo Schedule of Classes, 202608: ANSC447 prerequisite 'Must have completed or be concurrently enrolled in ANSC446.'" },
  { lecture: "ANSC212", labs: ["ANSC214"], source: "Testudo Schedule of Classes, 202501: ANSC214 prerequisite 'Must have completed or be concurrently enrolled in ANSC212.'" },
  { lecture: "BSCI170", labs: ["BSCI171"], source: "Testudo Schedule of Classes, 202601: BSCI171 'Basic laboratory principles of biology with special emphasis on cellular and molecular biology'; UMD catalog corequisite of BSCI170" },
];

export const STANDALONE: StandaloneLab[] = [
  { id: "ANTH222", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "BSCI202", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "BSCI379L", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "BSCI389L", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "BSCI399L", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "BSCI414", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "BSCI455", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "CINE319P", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "CMSC437", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "EDHD798", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENAE464", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENEB408B", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENEE245", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENEE305", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENEE427", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENEE445", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENEE459B", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENEE461", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENEE473", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENFP420", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENFP620", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENME461", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "ENMT362", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "GEOG212", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "HESP648A", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "HESP648B", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "HESP728", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "HESP729", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "HLTH489", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "INST406", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "KNES288", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "KNES300", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "KNES320", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "KNES360", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202701" },
  { id: "KNES385", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "LING248", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "LING448", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202701" },
  { id: "ANSC260", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202608" },
  { id: "CCJS320", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202608" },
  { id: "CHBE437", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202608" },
  { id: "DANC699", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202608" },
  { id: "ENEB408A", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202608" },
  { id: "ENEE416", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202608" },
  { id: "ENEE459L", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202608" },
  { id: "ENEE467", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202608" },
  { id: "ENEE486", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202608" },
  { id: "ENEE493", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202608" },
  { id: "ENEE789D", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202608" },
  { id: "ENMA466", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202608" },
  { id: "ENMA683", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202608" },
  { id: "ENME432", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202608" },
  { id: "HISP619T", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202608" },
  { id: "JOUR368K", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202608" },
  { id: "JOUR668K", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202608" },
  { id: "JOUR479Q", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202605" },
  { id: "BDBA813", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202601" },
  { id: "BIOE489J", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202601" },
  { id: "CCJS318J", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202601" },
  { id: "ENEE415", reason: "prerequisite is completed before the course; not taken with a lecture", source: "Testudo Schedule of Classes, 202601" },
  { id: "ENEE428", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202601" },
  { id: "ENMA417", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202601" },
  { id: "DANC689T", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202501" },
  { id: "ENEE419M", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202501" },
  { id: "ENMA489M", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202501" },
  { id: "HISP319T", reason: "self-contained course; text names no lecture partner", source: "Testudo Schedule of Classes, 202501" },
  { id: "KNES389Y", reason: "research, practicum, capstone or topics course; no lecture partner", source: "Testudo Schedule of Classes, 202501" },
  { id: "ANSC497", reason: "prerequisite is completed before the course; not taken with a lecture", source: "UMD catalog, https://academiccatalog.umd.edu/undergraduate/approved-courses/ansc/" },
  { id: "ANTH345", reason: "research, practicum, capstone or topics course; no lecture partner", source: "UMD catalog, https://academiccatalog.umd.edu/undergraduate/approved-courses/anth/" },
  { id: "CHBE485", reason: "self-contained course; text names no lecture partner", source: "UMD catalog, https://academiccatalog.umd.edu/undergraduate/approved-courses/chbe/" },
  { id: "ENAE364", reason: "prerequisite is completed before the course; not taken with a lecture", source: "UMD catalog, https://academiccatalog.umd.edu/undergraduate/approved-courses/enae/" },
  { id: "ENEB408", reason: "research, practicum, capstone or topics course; no lecture partner", source: "UMD catalog, https://academiccatalog.umd.edu/undergraduate/approved-courses/eneb/" },
  { id: "GEOG418", reason: "research, practicum, capstone or topics course; no lecture partner", source: "UMD catalog, https://academiccatalog.umd.edu/undergraduate/approved-courses/geog/" },
  { id: "EDHD768", reason: "self-contained course; text names no lecture partner", source: "UMD catalog, https://academiccatalog.umd.edu/graduate/courses/edhd/" },
  { id: "ENME740", reason: "research, practicum, capstone or topics course; no lecture partner", source: "UMD catalog, https://academiccatalog.umd.edu/graduate/courses/enme/" },
];

export const RULES: StandaloneRule[] = [
  { prefix: "ARTT", reason: "studio art courses meet as labs; no separate lecture", source: "Testudo Schedule of Classes: every ARTT course listed meets as Lab only" },
  { prefix: "DANC", reason: "dance technique and studio courses meet as labs; no separate lecture", source: "Testudo Schedule of Classes: every DANC course listed meets as Lab only" },
  { prefix: "KNES1", reason: "physical activity courses meet as labs; no separate lecture", source: "Testudo Schedule of Classes: every KNES1xx activity course listed meets as Lab only" },
];
